### ISSUE TITLE
Problem with 2020/04/29 data

### ISSUE THREAD

**Issue by ZFTurbo** [grwlf/COVID-19_plus_Russia#2]
You have some problem with data for 2020/04/29 - it's from today report.

For example last 3 numbers for Moscow:
45351,48426,53739

**Comment by sergei-mironov** [comment]
Hi, could you please clarify the issue?

Note: `04-29-2020.csv` file currently contains the following line on Moscow

```
,,"Moscow",Russia,2020-04-30 07:53:01,55.75222,37.61556,53739,611,5135,47993,"Moscow,Russia"
```

**Comment by ZFTurbo** [comment]
Sorry forgot to mension the file. You have error in here:
https://github.com/grwlf/COVID-19_plus_Russia/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_RU.csv

You have the same value for 2020/04/29 and 2020/04/30 columns. You have incorrect data for 2020/04/29.

You can find correct data for example here:
https://github.com/ZFTurbo/Covid-19-spread-prediction/blob/master/input/timedata/time_table_full_2020.04.29.csv

**Comment by sergei-mironov** [comment]
OK, I see now. Looks like the moments of time at which I sampled the Yandex measurements didn't match the moments when counters were actually updated. As a result, 2020/04/29 and 2020/04/30 shows same numbers. I'll think about including the file you've mentioned. Thanks.

**Comment by IVanDeryabin76** [comment]
Hello! Are you going to fix 29/04 - 30/04 problem?

**Comment by sergei-mironov** [comment]
Could you please check the branch 'fix-2020-04-29' ?

**Comment by IVanDeryabin76** [comment]
I can not find it

**Comment by sergei-mironov** [comment]
It's in a separate branch. See https://github.com/grwlf/COVID-19_plus_Russia/tree/fix-2020-04-29 for web access or type
```sh
git clone https://github.com/grwlf/COVID-19_plus_Russia
cd COVID-19_plus_Russia
git checkout fix-2020-04-29
```

**Comment by IVanDeryabin76** [comment]
Yes. Thanks, it works.

**Comment by sergei-mironov** [comment]
Merged into master

**Comment by sergei-mironov** [comment]
Could you please check 71ff0d03b5aa18 ?

**Comment by sergei-mironov** [comment]
Closing for now.
