### ISSUE TITLE
06 may data is not correct. 

### ISSUE THREAD

**Issue by IVanDeryabin76** [grwlf/COVID-19_plus_Russia#4]
In Moscow confirmed  it should be 92 676 on m May 6 according to стопкороновирус.рф
But in your dataset it is 85 973 on may 6
Please fix

**Comment by MishaDav** [comment]
На Яндекс картах 6 мая - 85973 как раз. А вот 7 мая 92676, а не 98522.

**Comment by IVanDeryabin76** [comment]
Так где ж правильный источник? Яндекс или стопкороновирус? 
на стопокороновирус 98 522 (7 мая) -92 767 (6 мая)

**Comment by IVanDeryabin76** [comment]
На Яндекс тоже статистике 98 522 (7 мая) -92 767 (6 мая).
https://yandex.ru/covid19/stat 
Откуда 85 973 взялось?

**Comment by MishaDav** [comment]
> На Яндекс тоже статистике 98 522 (7 мая) -92 767 (6 мая).
> https://yandex.ru/covid19/stat
> Откуда 85 973 взялось?

Если смотреть на диаграмму, то 6 мая - 85973. Другой вопрос, что последние данные указаны на 8 мая, которое ещё не кончилось.

https://datalens.yandex/r8r2cldmwff6n?56667170-2453-459b-a0ae-635d2e7fcfd2=Москва

**Comment by sergei-mironov** [comment]
Up to this moment I tried to include Yandex data with timestamps close enough to the upstream's timestamps. Upstream currently samples day X at 02:30 of day X+1 (+-1 hour). For example, file named '05-06-2020.csv' contains data with timestamp 05-07-2020 02:32 UTC. I included Russian data of 05-07-2020 03:22 UTC (the minimum timestamp I have which is >= upstream's).

* Sometimes I failed to follow this rule and included data stamped with ~08:00. I think this resulted in e.g. #2.

**Comment by sergei-mironov** [comment]
> На Яндекс тоже статистике 98 522 (7 мая) -92 767 (6 мая).
> https://yandex.ru/covid19/stat
> Откуда 85 973 взялось?

I'll check it soon

**Comment by IVanDeryabin76** [comment]
Hello! Again not correct on 8 may
REported 98522 for 07/05 and for 08/05 the same figure
Bot for 08/05 it was reported 10 189

Please fix.

**Comment by sergei-mironov** [comment]
Please check the detailed plot.
![image](https://user-images.githubusercontent.com/4477729/81497271-17481000-92c6-11ea-8aaf-5577d997b351.png)

(*edit: I'll add some explanations: orange dots is the data that I actually included in the dataset, blue dots are all Yandex dumps which I've made. Green vertical lines are timestamps of HSSE daily updates. The original intention was to report measurements closer to green lines)

My conclusions are:

1. 06 may data is actually correct
2. 07-08 may is indeed not correct and should be fixed


@IVanDeryabin76  Do you agree?

**Comment by techoracle** [comment]
Dear @grwlf, 

I found the data in 
OVID-19_plus_Russia/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_RU.csv 
are duplicated for 7.Mai and for 8.Mai. The both columns have the same values.
It seems the data on 7.Mai are wrong and missing.
Could you correct the 7.Mai, please!

Thanks in advance!

I am starting to use your data in https://covid-trend.info/#/ru/russia and appreciate your work, thanks for this!

**Comment by sergei-mironov** [comment]
@techoracle fixed 05-07-2020 and timelines, please check

**Comment by techoracle** [comment]
> @techoracle fixed 05-07-2020 and timelines, please check

yes, it's running very well now, thanks a lot for your fast fix!
