### ISSUE TITLE
Hello! No update today?

### ISSUE THREAD

**Issue by IVanDeryabin76** [grwlf/COVID-19_plus_Russia#5]

**Comment by sergei-mironov** [comment]
Hi, sorry for the delay. 2 things has happened:

1. Upstream started to publish russian details by themselves
2. They use different spelling for region names (and they publish only 83 regions of 85. I think that the missing ones are Crimea and all-in-one-Russia)

**Comment by sergei-mironov** [comment]
For now I'll continue to update my repo as-is. My plan is:

1. Change the names of existing regions according to the upstream spelling. This may take some time. I'm working on it.
2. Continue to update data for Crimea
3. Automate the updating process.

**Comment by sergei-mironov** [comment]
I will not update plots before the names are fixed.

**Comment by sergei-mironov** [comment]
Should be fixed now.
