### ISSUE TITLE
RU time series are not updated since 31. May

### ISSUE THREAD

**Issue by techoracle** [grwlf/COVID-19_plus_Russia#6]
Please have a look at 
- time_series_covid19_confirmed_RU.csv
- time_series_covid19_deaths_RU.csv
from the folder COVID-19_plus_Russia/csse_covid_19_data/csse_covid_19_time_series/

I see they were updated "yesterday" in Git, but there are only data up to 31. May inside.
Is it a new issue or already known?

**Comment by sergei-mironov** [comment]
Sorry, this is because of big changes in the upstream. Should be fixed now.

**Comment by sergei-mironov** [comment]
Note that I changed the spelling of region names to match the upstream

**Comment by techoracle** [comment]
Thanks a lot for your efforts
